.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" --------------------------------------------------------------------------
.TH "CONFETTI" "3" "April 9th 2025" "Confetti 1.0.0-beta"
.SH NAME
conf_get_comment, conf_get_comment_count \- retrieve comments
.\" --------------------------------------------------------------------------
.SH LIBRARY
Configuration parser (libconfetti, -lconfetti)
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <confetti.h>
.PP
.BI "const conf_comment *conf_get_comment(const conf_unit *" unit ", long " index ");"
.BI "long conf_get_comment_count(const conf_unit *" unit ");"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
The \fBconf_get_comment\fR() function returns the comment at \fIindex\fR for the Confetti configuration \fIunit\fR.
The pseudo directive returned is associated with \fIunit\fR and is freed when it's released with \fBconf_free\fR(3).
.PP
The \fBconf_get_comment_count\fR() function returns the number of comments discovered in the Confetti configuration \fIunit\fR.
.\" --------------------------------------------------------------------------
.SS Comment structure
The \fBconf_comment\fR structure includes the following fields:
.PP
.in +4n
.EX
size_t offset;
size_t length;
.EE
.in
.PP
The \fIoffset\fR and \fIlength\fR fields describe the span of UTF-8 code units of the comment in the Confetti source text.
.\" --------------------------------------------------------------------------
.SH RETURN VALUE
.SH RETURN VALUE
The \fBconf_get_comment\fR() function returns the comment at \fIindex\fR for the Confetti configuration \fIunit\fR.
If \fIindex\fR is out-of-bounds or \fIunit\fR is NULL, then NULL is returned.
.PP
The \fBconf_get_comment_count\fR() function returns the number of comments for the Confetti configuration \fIunit\fR.
.\" --------------------------------------------------------------------------
.SH LICENSING
Confetti is Open Source software distributed under the MIT License.
Please see the LICENSE file included with the Confetti distribution for details.
