.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" --------------------------------------------------------------------------
.TH "CONFETTI" "3" "April 9th 2025" "Confetti 0.6.0"
.SH NAME
conf_get_argument, conf_get_argument_count \- retrieve a directive's argument
.\" --------------------------------------------------------------------------
.SH LIBRARY
Configuration parser (libconfetti, -lconfetti)
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <confetti.h>
.PP
.BI "const conf_argument *conf_get_argument(const conf_directive *" dir ", long " index ");"
.BI "long conf_get_argument_count(const conf_directive *" dir ");"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
The \fBconf_get_argument\fR() function returns the argument at \fIindex\fR for directive \fIdir\fR.
The argument returned is associated with its configuration unit and is freed when the unit is released with \fBconf_free\fR(3).
.PP
The \fBconf_get_argument_count\fR() function returns the number of arguments \fIdir\fR has.
.\" --------------------------------------------------------------------------
.SS Argument structure
The \fBconf_argument\fR structure includes the following fields:
.PP
.in +4n
.EX
const char *value;
size_t lexeme_offset;
size_t lexeme_length;
bool is_expression;
.EE
.in
.PP
The \fIvalue\fR field is the evaluated argument as a null-terminated UTF-8 encoded string.
The memory \fIvalue\fR points to is freed with the configuration unit via \fBconf_free\fR(3).
.PP
The \fIlexeme_offset\fR and \fIlexeme_length\fR fields describe the span of UTF-8 code units of the argument in the Confetti source text.
.PP
The \fIis_expression\fR field, if true, indicates the argument is an expression argument.
Expression arguments are arguments enclosed in parentheses.
Expression arguments are a language extension enabled via the \fIconf_extensions\fR structure.
.\" --------------------------------------------------------------------------
.SH RETURN VALUE
The argument or argument count for the Confetti directive \fIdir\fR.
If \fIindex\fR is out-of-bounds or \fIdir\fR is NULL, then NULL is returned.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR conf_get_directive (3),
.BR conf_get_directive_count (3)
.\" --------------------------------------------------------------------------
.SH LICENSING
Confetti is Open Source software distributed under the MIT License.
Please see the LICENSE file included with the Confetti distribution for details.
