.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" --------------------------------------------------------------------------
.TH "CONFETTI" "3" "April 2nd 2025" "Confetti 0.2.1"
.SH NAME
conf_get_argument, conf_get_argument_count \- retrieve a directive's argument
.\" --------------------------------------------------------------------------
.SH LIBRARY
Configuration parser (libconfetti, -lconfetti)
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <confetti.h>
.PP
.BI "conf_argument *conf_get_argument(conf_dir *" dir ", long " index ");"
.BI "long conf_get_argument_count(conf_dir *" dir ");"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
The \fBconf_get_argument\fR function returns the argument at \fIindex\fR for directive \fIdir\fR.
.PP
The \fBconf_get_argument_count\fR function returns the number of arguments \fIdir\fR has.
.\" --------------------------------------------------------------------------
.SS Argument structure
The \fBconf_argument\fR structure includes the following fields:
.PP
.in +4n
.EX
size_t lexeme_offset;
size_t lexeme_length;
const char *value;
.EE
.in
.PP
The \fIvalue\fR field is the argument as a null-terminated UTF-8 encoded string.
The \fIlexeme_offset\fR and \fIlexeme_length\fR fields describe the span of UTF-8 code units of the argument in the Confetti source text.
.\" --------------------------------------------------------------------------
.SH RETURN VALUE
The argument or argument count for the Confetti directive \fIdir\fR.
If \fIindex\fR is out-of-bounds or \fIdir\fR is \fCNULL\fR, then \fCNULL\fR is returned.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR conf_get_subdirective (3),
.BR conf_get_subdirective_count (3)
.\" --------------------------------------------------------------------------
.SH LICENSING
Confetti is Free Software distributed under the MIT License.
Please see the LICENSE file included with the Confetti distribution for details.
