.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" --------------------------------------------------------------------------
.TH "CONFETTI" "3" "April 3rd 2025" "Confetti 0.3.0"
.SH NAME
conf_get_comment, conf_get_comment_count \- retrieve comments
.\" --------------------------------------------------------------------------
.SH LIBRARY
Configuration parser (libconfetti, -lconfetti)
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <confetti.h>
.PP
.BI "conf_comment *conf_get_comment(conf_document *" doc ", long " index ");"
.BI "long conf_get_comment_count(conf_document *" doc ");"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
The \fBconf_get_comment\fR function returns the comment at \fIindex\fR for the Confetti document \fIdoc\fR.
.PP
The \fBconf_get_comment_count\fR function returns the number of comments discovered in the Confetti document \fIdoc\fR.
.\" --------------------------------------------------------------------------
.SS Comment structure
The \fBconf_comment\fR structure includes the following fields:
.PP
.in +4n
.EX
size_t offset;
size_t length;
.EE
.in
.PP
The \fIoffset\fR and \fIlength\fR fields describe the span of UTF-8 code units of the comment in the Confetti source text.
.\" --------------------------------------------------------------------------
.SH RETURN VALUE
The comment or comment count for the Confetti document \fIdoc\fR.
If \fIindex\fR is out-of-bounds or \fIdoc\fR is \fCNULL\fR, then \fCNULL\fR is returned.
.\" --------------------------------------------------------------------------
.SH LICENSING
Confetti is Free Software distributed under the MIT License.
Please see the LICENSE file included with the Confetti distribution for details.
