name: Bug Report
description: Report a bug in the reference implementation or language specification.

body:
- type: markdown
  attributes:
    value: |

      If you're reporting a bug in the C implementation, then please include a minimal, but complete example that reproduces the issue.

      Confetti is a passion project. If you need extensive support, then please reach out through my software company: https://railgunlabs.com/services/.

- type: textarea
  id: suggestion
  attributes:
    label: bug
    description: Report a bug in the reference implementation or language specification.
    placeholder: Please include a complete example.
  validations:
    required: true
