name: Build Status
on: [push, pull_request]
jobs:
  confetti:
    name: "Build ${{ matrix.platform.NAME }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { CC: gcc,   NAME: 'GCC'   }
        - { CC: clang, NAME: 'Clang' }
    env:
      AUDITION_USER: ${{ secrets.AuditionUser }}
      AUDITION_KEY: ${{ secrets.AuditionKey }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Dependencies
      run: |
        curl -L -o audition.deb https://github.com/RailgunLabs/audition/releases/download/v1.0.3/libaudition_1.0.3-1_amd64.deb
        sudo dpkg -i audition.deb
        sudo apt-get install -y ninja-build
        sudo apt-get install -y lcov
        sudo apt-get install -y valgrind
    - name: Generate Unicode Data
      run: |
        python unicode.py --download
        python unicode.py
    - name: Build and Test
      env:
        CC: ${{ matrix.platform.CC }}
      run: |
        cd tests && ./test.sh
    - name: Release Process
      env:
        CC: ${{ matrix.platform.CC }}
      run: |
        ./autogen.sh
        ./configure --verbose
        make
        make distcheck
