name: Build Status
on: [push, pull_request, workflow_dispatch]
jobs:
  windows:
    name: "Windows - Visual Studio"
    runs-on: windows-latest
    env:
      AUDITION_USER: ${{ secrets.AuditionUser }}
      AUDITION_KEY: ${{ secrets.AuditionKey }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        Invoke-WebRequest -OutFile audition.msi -Uri https://github.com/railgunlabs/audition/releases/download/v1.0.5/Audition-1.0.5-x64.msi
        msiexec /i audition.msi /quiet /norestart
        echo "PATH=$env:PATH;$env:LOCALAPPDATA\Programs\Audition" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Generate Unicode Data
      run: |
        python unicode.py --download
        python unicode.py
    - name: Build and Test in Debug
      run: |
        cmake -B build -DCONFETTI_BUILD_TESTS=ON
        cmake --build build --config Debug
        ctest --output-on-failure --test-dir build -C Debug
    - name: Build and Test in Release
      run: |
        cmake -B build -DCONFETTI_BUILD_TESTS=ON
        cmake --build build --config Release
        ctest --output-on-failure --test-dir build -C Release
