name: Build Status
on: [push, pull_request, workflow_dispatch]
jobs:
  linux:
    name: "Linux - ${{ matrix.platform.NAME }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { CC: gcc,   NAME: 'GCC'   }
        - { CC: clang, NAME: 'Clang' }
    env:
      AUDITION_USER: ${{ secrets.AuditionUser }}
      AUDITION_KEY: ${{ secrets.AuditionKey }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Dependencies
      run: |
        curl -L -o audition.deb https://github.com/railgunlabs/audition/releases/download/v1.0.3/libaudition_1.0.3-1_amd64.deb
        sudo dpkg -i audition.deb
        sudo apt-get install -y ninja-build
        sudo apt-get install -y lcov
        sudo apt-get install -y valgrind
    - name: Generate Unicode Data
      run: |
        python unicode.py --download
        python unicode.py
    - name: Build and Test
      env:
        CC: ${{ matrix.platform.CC }}
      run: |
        cd tests && ./test.sh
    - name: Release Process
      env:
        CC: ${{ matrix.platform.CC }}
      run: |
        ./autogen.sh
        ./configure --verbose
        make
        make distcheck
  windows:
    name: "Windows - Visual Studio"
    runs-on: windows-latest
    env:
      AUDITION_USER: ${{ secrets.AUDITION_USER }}
      AUDITION_KEY: ${{ secrets.AUDITION_KEY }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        Invoke-WebRequest -OutFile audition.msi -Uri https://github.com/railgunlabs/audition/releases/download/v1.0.3/Audition-1.0.3-x64.msi
        msiexec /i audition.msi /quiet /norestart
        echo "PATH=$env:PATH;$env:LOCALAPPDATA\Programs\Audition" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Build and Test in Debug
      run: |
        cmake -B build -DCONFETTI_BUILD_TESTS=ON
        cmake --build build --config Debug
        ctest --output-on-failure --test-dir build -C Debug
    - name: Build and Test in Release
      run: |
        cmake -B build -DCONFETTI_BUILD_TESTS=ON
        cmake --build build --config Release
        ctest --output-on-failure --test-dir build -C Release
